# Generated by Django 5.0.7 on 2024-07-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_data', '0002_alter_building_asset_acquisition_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='attachments',
        ),
    ]
