basePath: /api/v1
host: localhost:3000
info:
  contact:
    email: goggxi@gmail.com
    name: Moh Rifkan
    url: https://github.com/Goggxi
  description: This is a simple songs API
  title: Songs API
  version: "1"
paths: {}
swagger: "2.0"
