basePath: /api/v1
definitions:
  api.Album:
    properties:
      artist:
        $ref: '#/definitions/api.Artist'
      created_at:
        example: "2024-07-18T16:19:49.703231Z"
        type: string
      genre:
        example: Pop
        type: string
      id:
        example: f4ff0500-7dcd-4f28-9e3e-77859a02977
        type: string
      release_date:
        example: "2021-08-01T00:00:00Z"
        type: string
      title:
        example: Album Title
        type: string
      updated_at:
        example: "2024-07-18T16:19:49.703231Z"
        type: string
    type: object
  api.AlbumReq:
    properties:
      artist_id:
        example: f4ff0500-7dcd-4f28-9e3e-77859a02977
        type: string
      genre:
        example: Pop
        type: string
      release_date:
        example: "2024-07-18T16:19:49.703231Z"
        type: string
      title:
        example: Album Title
        type: string
    required:
    - artist_id
    - genre
    - title
    type: object
  api.Artist:
    properties:
      bio:
        example: Lorem ipsum dolor sit amet
        type: string
      created_at:
        example: "2024-07-18T16:19:49.703231Z"
        type: string
      id:
        example: f4ff0500-7dcd-4f28-9e3e-77859a02977
        type: string
      name:
        example: John Doe
        type: string
      updated_at:
        example: "2024-07-18T16:19:49.703231Z"
        type: string
    type: object
  api.ArtistReq:
    properties:
      bio:
        example: Lorem ipsum dolor sit amet
        type: string
      name:
        example: John Doe
        type: string
    required:
    - name
    type: object
  api.Song:
    properties:
      album:
        $ref: '#/definitions/api.Album'
      created_at:
        example: "2024-07-18T16:19:49.703231Z"
        type: string
      duration:
        example: 60
        type: integer
      id:
        example: f4ff0500-7dcd-4f28-9e3e-77859a02977
        type: string
      release_date:
        example: "2024-07-18T16:19:49.703231Z"
        type: string
      title:
        example: Song Title
        type: string
      updated_at:
        example: "2024-07-18T16:19:49.703231Z"
        type: string
    type: object
  api.SongReq:
    properties:
      album_id:
        example: f4ff0500-7dcd-4f28-9e3e-77859a02977
        type: string
      duration:
        example: 60
        type: integer
      release_date:
        example: "2024-07-18T16:19:49.703231Z"
        type: string
      title:
        example: Song Title
        type: string
    required:
    - album_id
    - duration
    - title
    type: object
  utils.ErrorResponse:
    properties:
      error: {}
      message:
        example: error
        type: string
    type: object
  utils.SuccessResponse:
    properties:
      data: {}
      message:
        example: success
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: goggxi@gmail.com
    name: Moh Rifkan
    url: https://github.com/Goggxi
  description: This is a simple songs API
  title: Songs API
  version: "1"
paths:
  /albums:
    get:
      consumes:
      - application/json
      description: Get all albums
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/api.Album'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Get all albums
      tags:
      - albums
    post:
      consumes:
      - application/json
      description: Create a new album
      parameters:
      - description: Album request
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/api.AlbumReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.Album'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Create a new album
      tags:
      - albums
  /albums/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an album by ID
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Delete an album by ID
      tags:
      - albums
    get:
      consumes:
      - application/json
      description: Get an album by ID
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.Album'
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Get an album by ID
      tags:
      - albums
    put:
      consumes:
      - application/json
      description: Update an album
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: string
      - description: Album request
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/api.AlbumReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.Album'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Update an album
      tags:
      - albums
  /artists:
    get:
      consumes:
      - application/json
      description: Get all artists
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/api.Artist'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Get all artists
      tags:
      - artists
    post:
      consumes:
      - application/json
      description: Create a new artist
      parameters:
      - description: Artist request
        in: body
        name: artist
        required: true
        schema:
          $ref: '#/definitions/api.ArtistReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.Artist'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Create a new artist
      tags:
      - artists
  /artists/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an artist by ID
      parameters:
      - description: Artist ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Delete an artist by ID
      tags:
      - artists
    get:
      consumes:
      - application/json
      description: Get an artist by ID
      parameters:
      - description: Artist ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.Artist'
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Get an artist by ID
      tags:
      - artists
    put:
      consumes:
      - application/json
      description: Update an artist
      parameters:
      - description: Artist ID
        in: path
        name: id
        required: true
        type: string
      - description: Artist request
        in: body
        name: artist
        required: true
        schema:
          $ref: '#/definitions/api.ArtistReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.Artist'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Update an artist
      tags:
      - artists
  /songs:
    get:
      consumes:
      - application/json
      description: Get all songs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/api.Song'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Get all songs
      tags:
      - songs
    post:
      consumes:
      - application/json
      description: Create a new song
      parameters:
      - description: Song request
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/api.SongReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.Song'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Create a new song
      tags:
      - songs
  /songs/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a song by ID
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Delete a song by ID
      tags:
      - songs
    get:
      consumes:
      - application/json
      description: Get a song by ID
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.Song'
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Get a song by ID
      tags:
      - songs
    put:
      consumes:
      - application/json
      description: Update a song
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: string
      - description: Song request
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/api.SongReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/api.Song'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/utils.ErrorResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Update a song
      tags:
      - songs
swagger: "2.0"
